# Bundled seed questions (used on first startup before fetch completes)
# Format: (question, A, B, C, D, correct)

QUIZ_SEED = {
    "space": [
        ("Which planet is known as the Red Planet?", "Venus", "Mars", "Jupiter", "Saturn", "B"),
        ("Largest planet in our solar system?", "Earth", "Saturn", "Jupiter", "Neptune", "C"),
        ("How many moons does Earth have?", "1", "2", "3", "0", "A"),
        ("Which planet has the most moons?", "Jupiter", "Saturn", "Uranus", "Neptune", "B"),
        ("Closest planet to the Sun?", "Venus", "Earth", "Mercury", "Mars", "C"),
        ("Which planet has prominent rings?", "Mars", "Saturn", "Venus", "Mercury", "B"),
        ("What galaxy is Earth in?", "Andromeda", "Milky Way", "Sombrero", "Whirlpool", "B"),
        ("Hottest planet?", "Mercury", "Venus", "Mars", "Jupiter", "B"),
        ("How many planets in solar system?", "7", "8", "9", "10", "B"),
        ("Which planet spins fastest?", "Earth", "Jupiter", "Saturn", "Mars", "B"),
        ("What is the Sun mainly made of?", "Oxygen", "Hydrogen", "Helium", "Carbon", "B"),
        ("Which is the largest moon?", "Titan", "Ganymede", "Europa", "Io", "B"),
        ("How far is Sun from Earth (AU)?", "0.5", "1", "2", "5", "B"),
        ("Which planet is coldest?", "Mars", "Jupiter", "Neptune", "Uranus", "C"),
        ("What is a shooting star?", "Star", "Meteor", "Planet", "Comet", "B"),
    ],
    "general": [
        ("Capital of France?", "London", "Paris", "Rome", "Berlin", "B"),
        ("Who wrote Romeo and Juliet?", "Dickens", "Shakespeare", "Tolstoy", "Twain", "B"),
        ("Largest ocean?", "Atlantic", "Indian", "Pacific", "Arctic", "C"),
        ("Which gas do plants absorb?", "Oxygen", "Nitrogen", "CO2", "Helium", "C"),
        ("How many continents?", "5", "6", "7", "8", "C"),
        ("Largest mammal?", "Elephant", "Blue Whale", "Giraffe", "Rhino", "B"),
        ("Currency of Japan?", "Yuan", "Won", "Yen", "Dollar", "C"),
        ("Fastest land animal?", "Lion", "Tiger", "Cheetah", "Leopard", "C"),
        ("Smallest prime number?", "0", "1", "2", "3", "C"),
        ("Chemical symbol for gold?", "Gd", "Au", "Ag", "Go", "B"),
        ("Which country invented pizza?", "France", "Italy", "Greece", "Spain", "B"),
        ("Days in a leap year?", "364", "365", "366", "367", "C"),
        ("Largest desert?", "Sahara", "Gobi", "Antarctic", "Kalahari", "C"),
        ("What does CPU stand for?", "Central Unit", "Computer Unit", "Central Processing Unit", "Core Unit", "C"),
        ("First man on moon?", "Aldrin", "Armstrong", "Gagarin", "Glenn", "B"),
    ],
    "science": [
        ("Chemical symbol for water?", "H2O", "CO2", "O2", "NaCl", "A"),
        ("Hardest natural substance?", "Gold", "Iron", "Diamond", "Silver", "C"),
        ("How many bones in human body?", "196", "206", "216", "226", "B"),
        ("What gas do we breathe out?", "Oxygen", "Nitrogen", "CO2", "Helium", "C"),
        ("Speed of light (km/s)?", "300,000", "150,000", "450,000", "600,000", "A"),
        ("Smallest unit of life?", "Atom", "Molecule", "Cell", "Organ", "C"),
        ("What does DNA stand for?", "Deoxyribonucleic Acid", "Dinucleic Acid", "Deoxy Acid", "Dynamic Acid", "A"),
        ("Powerhouse of the cell?", "Nucleus", "Mitochondria", "Ribosome", "Chloroplast", "B"),
        ("Element with symbol 'O'?", "Gold", "Oxygen", "Osmium", "Oganesson", "B"),
        ("Which is a noble gas?", "Oxygen", "Hydrogen", "Helium", "Nitrogen", "C"),
        ("pH of pure water?", "5", "6", "7", "8", "C"),
        ("Which metal is liquid at room temp?", "Mercury", "Iron", "Gold", "Lead", "A"),
        ("How many teeth does an adult have?", "28", "30", "32", "34", "C"),
        ("What is the boiling point of water (C)?", "90", "100", "110", "120", "B"),
        ("Which planet has red spot?", "Mars", "Jupiter", "Saturn", "Venus", "B"),
    ],
    "history": [
        ("First US President?", "Lincoln", "Washington", "Jefferson", "Adams", "B"),
        ("When did WWII end?", "1943", "1944", "1945", "1946", "C"),
        ("Who built Taj Mahal?", "Akbar", "Shah Jahan", "Aurangzeb", "Babur", "B"),
        ("When did India get independence?", "1945", "1946", "1947", "1948", "C"),
        ("Who discovered America?", "Columbus", "Vasco da Gama", "Magellan", "Cook", "A"),
        ("First emperor of Rome?", "Julius Caesar", "Augustus", "Nero", "Constantine", "B"),
        ("The Great Wall is in?", "Japan", "Korea", "China", "Mongolia", "C"),
        ("Who invented the telephone?", "Edison", "Bell", "Tesla", "Marconi", "B"),
        ("Who was known as Iron Lady?", "Angela Merkel", "Margaret Thatcher", "Indira Gandhi", "Queen Victoria", "B"),
        ("French Revolution began in?", "1776", "1789", "1799", "1815", "B"),
        ("Who was the first man in space?", "Armstrong", "Gagarin", "Glenn", "Aldrin", "B"),
        ("Berlin Wall fell in?", "1987", "1988", "1989", "1990", "C"),
        ("First President of India?", "Nehru", "Rajendra Prasad", "Radhakrishnan", "Zakir Hussain", "B"),
        ("Who wrote Indian Constitution?", "Gandhi", "Ambedkar", "Nehru", "Patel", "B"),
        ("The Titanic sank in?", "1905", "1912", "1918", "1923", "B"),
    ],
    "geography": [
        ("Longest river?", "Amazon", "Nile", "Yangtze", "Mississippi", "B"),
        ("Largest country by area?", "China", "USA", "Russia", "Canada", "C"),
        ("Smallest country?", "Monaco", "Vatican City", "San Marino", "Nauru", "B"),
        ("Capital of Japan?", "Seoul", "Beijing", "Tokyo", "Bangkok", "C"),
        ("Which continent is Egypt in?", "Asia", "Europe", "Africa", "Australia", "C"),
        ("Tallest mountain?", "K2", "Everest", "Kangchenjunga", "Makalu", "B"),
        ("Most populated country?", "USA", "China", "India", "Russia", "C"),
        ("Capital of Australia?", "Sydney", "Melbourne", "Canberra", "Perth", "C"),
        ("Deepest ocean?", "Atlantic", "Indian", "Pacific", "Arctic", "C"),
        ("How many countries in the world?", "180", "185", "195", "200", "C"),
        ("Land of Rising Sun?", "China", "Korea", "Japan", "Vietnam", "C"),
        ("Sahara desert is in?", "Asia", "Africa", "Australia", "America", "B"),
        ("Saltiest sea?", "Red Sea", "Dead Sea", "Caspian", "Black Sea", "B"),
        ("Capital of Germany?", "Munich", "Berlin", "Hamburg", "Frankfurt", "B"),
        ("Which country has most time zones?", "Russia", "USA", "France", "China", "C"),
    ],
    "maths": [
        ("15% of 200?", "25", "30", "35", "20", "B"),
        ("Square root of 144?", "10", "11", "12", "13", "C"),
        ("Value of pi (approx)?", "3.14", "3.15", "3.16", "3.13", "A"),
        ("Sum of angles in triangle?", "90", "180", "270", "360", "B"),
        ("7 * 8 = ?", "54", "56", "58", "60", "B"),
        ("5 factorial = ?", "100", "110", "120", "130", "C"),
        ("1/2 + 1/4 = ?", "1/6", "2/6", "3/4", "1/4", "C"),
        ("Prime after 7?", "8", "9", "10", "11", "D"),
        ("2^10 = ?", "512", "1024", "2048", "256", "B"),
        ("Sides in a hexagon?", "5", "6", "7", "8", "B"),
        ("1 km = ? meters", "100", "500", "1000", "10000", "C"),
        ("100 / 4 = ?", "20", "25", "30", "35", "B"),
        ("Right angle = ? degrees", "45", "90", "180", "360", "B"),
        ("LCM of 4 and 6?", "8", "10", "12", "24", "C"),
        ("Decimal of 1/5?", "0.1", "0.2", "0.3", "0.5", "B"),
    ],
    "tech": [
        ("Founder of Microsoft?", "Steve Jobs", "Bill Gates", "Elon Musk", "Mark Zuckerberg", "B"),
        ("HTML stands for?", "Hyper Text Markup Language", "High Tech Modern Lang", "Home Tool Markup Lang", "Hyperlink Markup", "A"),
        ("Founder of Apple?", "Bill Gates", "Steve Jobs", "Jeff Bezos", "Larry Page", "B"),
        ("AI stands for?", "Auto Info", "Artificial Intelligence", "Active Input", "Auto Import", "B"),
        ("1 TB = ? GB", "100", "500", "1000", "10000", "C"),
        ("Who invented WWW?", "Bill Gates", "Tim Berners-Lee", "Steve Wozniak", "Linus Torvalds", "B"),
        ("iPhone is made by?", "Samsung", "Google", "Apple", "Nokia", "C"),
        ("RAM stands for?", "Random Access Memory", "Read All Memory", "Rapid Access Memory", "Runtime Access Mode", "A"),
        ("Language for Android apps?", "Python", "Kotlin", "Ruby", "PHP", "B"),
        ("1 Byte = ? bits", "4", "8", "16", "32", "B"),
        ("First computer was called?", "ENIAC", "IBM-PC", "Apple-1", "UNIVAC", "A"),
        ("YouTube is owned by?", "Apple", "Meta", "Google", "Microsoft", "C"),
        ("HTTP stands for?", "Hyper Text Transfer Protocol", "High Tech TP", "Home Tool Protocol", "Hyperlink Transfer Protocol", "A"),
        ("Founder of Facebook?", "Elon Musk", "Mark Zuckerberg", "Jeff Bezos", "Larry Ellison", "B"),
        ("What is 1 GB in MB?", "100", "512", "1024", "2048", "C"),
    ],
    "sports": [
        ("2011 Cricket World Cup winner?", "Australia", "India", "Sri Lanka", "Pakistan", "B"),
        ("Players in football team?", "9", "10", "11", "12", "C"),
        ("Olympics held every ? years", "2", "3", "4", "5", "C"),
        ("Shuttlecock is used in?", "Tennis", "Badminton", "Squash", "Table Tennis", "B"),
        ("God of Cricket?", "Kohli", "Tendulkar", "Dhoni", "Rohit", "B"),
        ("Players in basketball?", "4", "5", "6", "7", "B"),
        ("2016 Olympics host?", "China", "UK", "Brazil", "Japan", "C"),
        ("Hat-trick is used in?", "Cricket", "Football", "Hockey", "All of these", "D"),
        ("Grand Slams in tennis?", "3", "4", "5", "6", "B"),
        ("India's national sport?", "Cricket", "Hockey", "Kabaddi", "No official", "D"),
        ("Most Ballon d'Or wins?", "Ronaldo", "Messi", "Neymar", "Mbappe", "B"),
        ("Olympic rings?", "3", "4", "5", "6", "C"),
        ("Nadal plays?", "Tennis", "Golf", "Football", "Cricket", "A"),
        ("Olympic pool length?", "25m", "50m", "75m", "100m", "B"),
        ("Chess was invented in?", "China", "India", "Persia", "Greece", "B"),
    ],
    "movies": [
        ("Who directed Inception?", "Spielberg", "Nolan", "Cameron", "Scorsese", "B"),
        ("'May the Force be with you' from?", "Star Trek", "Star Wars", "Matrix", "Avatar", "B"),
        ("Who played Iron Man?", "Chris Evans", "Robert Downey Jr", "Chris Hemsworth", "Mark Ruffalo", "B"),
        ("Oscar 2020 Best Picture?", "1917", "Parasite", "Joker", "Once Upon a Time", "B"),
        ("Jack in Titanic?", "Brad Pitt", "Leonardo DiCaprio", "Johnny Depp", "Tom Cruise", "B"),
        ("Frozen was made by?", "Pixar", "Disney", "DreamWorks", "Warner Bros", "B"),
        ("King of Bollywood?", "Salman", "Aamir", "Shah Rukh", "Akshay", "C"),
        ("'Let It Go' from?", "Moana", "Frozen", "Tangled", "Encanto", "B"),
        ("Who directed Avatar?", "Nolan", "Cameron", "Spielberg", "Lucas", "B"),
        ("Joker in 2019?", "Heath Ledger", "Joaquin Phoenix", "Jared Leto", "Jack Nicholson", "B"),
        ("Character Forrest Gump played by?", "Tom Hanks", "Brad Pitt", "Tom Cruise", "Denzel", "A"),
        ("Thor played by?", "Chris Evans", "Chris Hemsworth", "Robert Downey", "Mark Ruffalo", "B"),
        ("Hogwarts in?", "Narnia", "Harry Potter", "Twilight", "Hunger Games", "B"),
        ("Who directed Titanic?", "Nolan", "Cameron", "Spielberg", "Scorsese", "B"),
        ("Lion King is from?", "Pixar", "Disney", "DreamWorks", "WB", "B"),
    ],
    "music": [
        ("King of Pop?", "Elvis", "Michael Jackson", "Prince", "Madonna", "B"),
        ("Guitar strings?", "4", "5", "6", "7", "C"),
        ("'Shape of You' by?", "Ed Sheeran", "Bruno Mars", "Drake", "Weeknd", "A"),
        ("'Bohemian Rhapsody' by?", "Beatles", "Queen", "Led Zeppelin", "Rolling Stones", "B"),
        ("India's national song?", "Vande Mataram", "Jana Gana Mana", "Sare Jahan Se", "Ae Mere Watan", "A"),
        ("'Sorry' by?", "Justin Bieber", "Shawn Mendes", "Ed Sheeran", "Bruno Mars", "A"),
        ("Piano keys?", "66", "76", "88", "98", "C"),
        ("Band with Paul McCartney?", "Queen", "Beatles", "Pink Floyd", "Rolling Stones", "B"),
        ("Queen of Pop?", "Beyonce", "Madonna", "Rihanna", "Taylor Swift", "B"),
        ("'Blinding Lights' by?", "The Weeknd", "Drake", "Post Malone", "Bruno Mars", "A"),
        ("Indian Grammy winner?", "A.R. Rahman", "Zakir Hussain", "Ravi Shankar", "All", "D"),
        ("'Rolling in the Deep' by?", "Adele", "Taylor Swift", "Rihanna", "Beyonce", "A"),
        ("Sitar player?", "Ravi Shankar", "Zakir", "Rahman", "Bismillah", "A"),
        ("National anthem writer?", "Tagore", "Bankim", "Gandhi", "Nehru", "A"),
        ("Highest female voice?", "Soprano", "Alto", "Tenor", "Bass", "A"),
    ],
    "animals": [
        ("Largest land animal?", "Elephant", "Giraffe", "Rhino", "Hippo", "A"),
        ("Fastest animal?", "Lion", "Cheetah", "Leopard", "Horse", "B"),
        ("Ship of desert?", "Horse", "Camel", "Donkey", "Elephant", "B"),
        ("Tallest animal?", "Elephant", "Giraffe", "Camel", "Horse", "B"),
        ("Spider legs?", "6", "8", "10", "12", "B"),
        ("Can't fly?", "Eagle", "Penguin", "Parrot", "Crow", "B"),
        ("Largest mammal?", "Elephant", "Blue Whale", "Giraffe", "Shark", "B"),
        ("Longest lifespan?", "Elephant", "Tortoise", "Whale", "Parrot", "B"),
        ("Produces silk?", "Ant", "Silkworm", "Bee", "Spider", "B"),
        ("King of jungle?", "Tiger", "Lion", "Elephant", "Leopard", "B"),
        ("Man's best friend?", "Cat", "Dog", "Horse", "Cow", "B"),
        ("Smallest bird?", "Sparrow", "Hummingbird", "Pigeon", "Crow", "B"),
        ("Can regrow tail?", "Lizard", "Snake", "Turtle", "Frog", "A"),
        ("Octopus hearts?", "1", "2", "3", "4", "C"),
        ("National animal of India?", "Lion", "Tiger", "Elephant", "Peacock", "B"),
    ],
    "food": [
        ("Red fruit with seeds outside?", "Apple", "Strawberry", "Cherry", "Mango", "B"),
        ("Pizza originated in?", "France", "Italy", "Greece", "Spain", "B"),
        ("Vegetable that makes you cry?", "Tomato", "Onion", "Potato", "Carrot", "B"),
        ("Yellow curved fruit?", "Apple", "Banana", "Mango", "Orange", "B"),
        ("Main ingredient of bread?", "Rice", "Flour", "Corn", "Barley", "B"),
        ("Spiciest pepper?", "Jalapeno", "Carolina Reaper", "Habanero", "Ghost Pepper", "B"),
        ("Sushi is from?", "China", "Korea", "Japan", "Thailand", "C"),
        ("Nutella nut?", "Almond", "Hazelnut", "Walnut", "Peanut", "B"),
        ("Most rice consumed in?", "USA", "China", "India", "Japan", "B"),
        ("Tofu made from?", "Milk", "Soy", "Wheat", "Rice", "B"),
        ("Oranges have vitamin?", "A", "B", "C", "D", "C"),
        ("Most coffee grown in?", "Brazil", "Colombia", "India", "Vietnam", "A"),
        ("Honey is made by?", "Ants", "Bees", "Wasps", "Butterflies", "B"),
        ("'Liquid gold'?", "Water", "Milk", "Olive Oil", "Honey", "C"),
        ("National fruit of India?", "Apple", "Mango", "Banana", "Orange", "B"),
    ],
    "literature": [
        ("Who wrote Hamlet?", "Dickens", "Shakespeare", "Tolstoy", "Twain", "B"),
        ("Who wrote War and Peace?", "Dostoevsky", "Tolstoy", "Chekhov", "Gorky", "B"),
        ("Who wrote 1984?", "Huxley", "Orwell", "Kafka", "Hemingway", "B"),
        ("Harry Potter author?", "Rowling", "Tolkien", "Lewis", "Martin", "A"),
        ("Pride and Prejudice author?", "Bronte", "Austen", "Eliot", "Woolf", "B"),
        ("The Alchemist author?", "Coelho", "Marquez", "Borges", "Neruda", "A"),
        ("Odyssey author?", "Homer", "Virgil", "Sophocles", "Plato", "A"),
        ("Divine Comedy author?", "Dante", "Petrarch", "Boccaccio", "Machiavelli", "A"),
        ("Faust author?", "Schiller", "Goethe", "Kafka", "Hesse", "B"),
        ("Don Quixote author?", "Cervantes", "Lorca", "Borges", "Marquez", "A"),
        ("To Kill a Mockingbird author?", "Lee", "Steinbeck", "Faulkner", "Fitzgerald", "A"),
        ("The Great Gatsby author?", "Hemingway", "Fitzgerald", "Faulkner", "Steinbeck", "B"),
        ("Moby Dick author?", "Melville", "Twain", "Hawthorne", "Poe", "A"),
        ("Ulysses author?", "Joyce", "Woolf", "Lawrence", "Forster", "A"),
        ("National poet of India?", "Tagore", "Bankim", "Gandhi", "Nehru", "A"),
    ],
    "politics": [
        ("Current UN Secretary-General?", "Ban Ki-moon", "António Guterres", "Kofi Annan", "Boutros Ghali", "B"),
        ("UN members?", "190", "193", "195", "200", "B"),
        ("UN headquarters?", "Geneva", "New York", "Paris", "London", "B"),
        ("First PM of India?", "Gandhi", "Nehru", "Patel", "Ambedkar", "B"),
        ("US Senators?", "50", "100", "150", "200", "B"),
        ("Oldest democracy?", "USA", "Greece", "India", "UK", "B"),
        ("EU formed in?", "1990", "1991", "1993", "1995", "C"),
        ("NATO stands for?", "North Atlantic Treaty Organization", "National Alliance Treaty Org", "North American Trade Org", "None", "A"),
        ("Country with no army?", "Japan", "Costa Rica", "Switzerland", "Norway", "B"),
        ("First President of India?", "Nehru", "Rajendra Prasad", "Radhakrishnan", "Zakir Hussain", "B"),
        ("Voting age in India?", "16", "18", "21", "25", "B"),
        ("Lok Sabha seats?", "500", "543", "545", "550", "C"),
        ("Rajya Sabha seats?", "240", "245", "250", "255", "B"),
        ("PM of India (2024)?", "Modi", "Rahul", "Kejriwal", "Mamata", "A"),
        ("US President (2025)?", "Biden", "Trump", "Obama", "Bush", "B"),
    ],
    "business": [
        ("Amazon founder?", "Gates", "Bezos", "Musk", "Jobs", "B"),
        ("Tesla founder?", "Bezos", "Musk", "Gates", "Cook", "B"),
        ("Richest person (2024)?", "Musk", "Bezos", "Arnault", "Gates", "A"),
        ("Tata is from?", "USA", "India", "UK", "Japan", "B"),
        ("Google's parent?", "Alphabet", "Meta", "Amazon", "Alibaba", "A"),
        ("GDP stands for?", "Gross Domestic Product", "General Development Plan", "Global Data Program", "Gross Data Product", "A"),
        ("Oldest stock market?", "NYSE", "NASDAQ", "LSE", "BSE", "A"),
        ("Bitcoin creator's alias?", "Nakamoto", "Satoshi", "Nakamura", "Hashimoto", "B"),
        ("World's largest company?", "Microsoft", "Apple", "Amazon", "Saudi Aramco", "D"),
        ("Rupee symbol designer?", "R.K. Joshi", "Ambani", "Tata", "Mistry", "A"),
        ("IPO stands for?", "Initial Public Offering", "Indian Public Offering", "Internal Payment Order", "Investment Portfolio", "A"),
        ("Warren Buffett known as?", "Oracle of Omaha", "King of Wall St", "Bond King", "Tech King", "A"),
        ("Largest economy?", "China", "USA", "Japan", "Germany", "B"),
        ("Alibaba founder?", "Jack Ma", "Pony Ma", "Musk", "Bezos", "A"),
        ("Inflation means?", "Price rise", "Price fall", "Stable prices", "Currency change", "A"),
    ],
}
